apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: es3e2z6qe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: es3e2z6qe-go 
  name: es3e2z6qe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: es3e2z6qe-go 
